export interface CountryData {
  name: string;
  code: string;
  cities: string[];
}

export const countriesData: CountryData[] = [
  {
    name: "Afghanistan",
    code: "AF",
    cities: ["Kabul", "Kandahar", "Herat", "Mazar-i-Sharif", "Jalalabad"],
  },
  {
    name: "Bangladesh",
    code: "BD",
    cities: [
      "Dhaka",
      "Chittagong",
      "Khulna",
      "Rajshahi",
      "Sylhet",
      "Barisal",
      "Rangpur",
      "Mymensingh",
      "Comilla",
      "Narayanganj",
    ],
  },
  {
    name: "India",
    code: "IN",
    cities: [
      "Mumbai",
      "Delhi",
      "Bangalore",
      "Hyderabad",
      "Chennai",
      "Kolkata",
      "Pune",
      "Ahmedabad",
      "Surat",
      "Jaipur",
      "Lucknow",
      "Kanpur",
      "Nagpur",
      "Indore",
      "Thane",
      "Bhopal",
      "Visakhapatnam",
      "Pimpri-Chinchwad",
      "Patna",
      "Vadodara",
    ],
  },
  {
    name: "Pakistan",
    code: "PK",
    cities: [
      "Karachi",
      "Lahore",
      "Faisalabad",
      "Rawalpindi",
      "Multan",
      "Gujranwala",
      "Hyderabad",
      "Peshawar",
      "Islamabad",
      "Quetta",
    ],
  },
  {
    name: "United States",
    code: "US",
    cities: [
      "New York",
      "Los Angeles",
      "Chicago",
      "Houston",
      "Phoenix",
      "Philadelphia",
      "San Antonio",
      "San Diego",
      "Dallas",
      "San Jose",
      "Austin",
      "Jacksonville",
      "Fort Worth",
      "Columbus",
      "Charlotte",
      "San Francisco",
      "Indianapolis",
      "Seattle",
      "Denver",
      "Boston",
    ],
  },
  {
    name: "United Kingdom",
    code: "GB",
    cities: [
      "London",
      "Birmingham",
      "Leeds",
      "Glasgow",
      "Sheffield",
      "Manchester",
      "Edinburgh",
      "Liverpool",
      "Bristol",
      "Cardiff",
      "Leicester",
      "Belfast",
      "Nottingham",
      "Newcastle",
      "Brighton",
    ],
  },
  {
    name: "Canada",
    code: "CA",
    cities: [
      "Toronto",
      "Montreal",
      "Vancouver",
      "Calgary",
      "Edmonton",
      "Ottawa",
      "Winnipeg",
      "Quebec City",
      "Hamilton",
      "Kitchener",
    ],
  },
  {
    name: "Australia",
    code: "AU",
    cities: [
      "Sydney",
      "Melbourne",
      "Brisbane",
      "Perth",
      "Adelaide",
      "Gold Coast",
      "Canberra",
      "Newcastle",
      "Wollongong",
      "Logan City",
    ],
  },
  {
    name: "Germany",
    code: "DE",
    cities: [
      "Berlin",
      "Hamburg",
      "Munich",
      "Cologne",
      "Frankfurt",
      "Stuttgart",
      "Düsseldorf",
      "Dortmund",
      "Essen",
      "Leipzig",
    ],
  },
  {
    name: "France",
    code: "FR",
    cities: [
      "Paris",
      "Marseille",
      "Lyon",
      "Toulouse",
      "Nice",
      "Nantes",
      "Strasbourg",
      "Montpellier",
      "Bordeaux",
      "Lille",
    ],
  },
  {
    name: "China",
    code: "CN",
    cities: [
      "Beijing",
      "Shanghai",
      "Guangzhou",
      "Shenzhen",
      "Chengdu",
      "Chongqing",
      "Tianjin",
      "Wuhan",
      "Hangzhou",
      "Xi'an",
      "Nanjing",
      "Suzhou",
    ],
  },
  {
    name: "Japan",
    code: "JP",
    cities: [
      "Tokyo",
      "Yokohama",
      "Osaka",
      "Nagoya",
      "Sapporo",
      "Fukuoka",
      "Kobe",
      "Kyoto",
      "Kawasaki",
      "Saitama",
    ],
  },
  {
    name: "South Korea",
    code: "KR",
    cities: [
      "Seoul",
      "Busan",
      "Incheon",
      "Daegu",
      "Daejeon",
      "Gwangju",
      "Suwon",
      "Ulsan",
      "Changwon",
      "Goyang",
    ],
  },
  {
    name: "Brazil",
    code: "BR",
    cities: [
      "São Paulo",
      "Rio de Janeiro",
      "Brasília",
      "Salvador",
      "Fortaleza",
      "Belo Horizonte",
      "Manaus",
      "Curitiba",
      "Recife",
      "Porto Alegre",
    ],
  },
  {
    name: "Mexico",
    code: "MX",
    cities: [
      "Mexico City",
      "Guadalajara",
      "Monterrey",
      "Puebla",
      "Tijuana",
      "León",
      "Juárez",
      "Zapopan",
      "Mérida",
      "Cancún",
    ],
  },
  {
    name: "Argentina",
    code: "AR",
    cities: [
      "Buenos Aires",
      "Córdoba",
      "Rosario",
      "Mendoza",
      "La Plata",
      "San Miguel de Tucumán",
      "Mar del Plata",
      "Salta",
      "Santa Fe",
      "San Juan",
    ],
  },
  {
    name: "South Africa",
    code: "ZA",
    cities: [
      "Johannesburg",
      "Cape Town",
      "Durban",
      "Pretoria",
      "Port Elizabeth",
      "Bloemfontein",
      "East London",
      "Pietermaritzburg",
      "Kimberley",
      "Nelspruit",
    ],
  },
  {
    name: "Nigeria",
    code: "NG",
    cities: [
      "Lagos",
      "Kano",
      "Ibadan",
      "Abuja",
      "Port Harcourt",
      "Benin City",
      "Kaduna",
      "Onitsha",
      "Warri",
      "Aba",
    ],
  },
  {
    name: "Egypt",
    code: "EG",
    cities: [
      "Cairo",
      "Alexandria",
      "Giza",
      "Shubra El-Kheima",
      "Port Said",
      "Suez",
      "Luxor",
      "Aswan",
      "Mansoura",
      "Tanta",
    ],
  },
  {
    name: "Kenya",
    code: "KE",
    cities: [
      "Nairobi",
      "Mombasa",
      "Kisumu",
      "Nakuru",
      "Eldoret",
      "Ruiru",
      "Kikuyu",
      "Kangundo-Tala",
      "Malindi",
      "Naivasha",
    ],
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    cities: [
      "Riyadh",
      "Jeddah",
      "Mecca",
      "Medina",
      "Dammam",
      "Khobar",
      "Tabuk",
      "Buraydah",
      "Khamis Mushait",
      "Hofuf",
    ],
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    cities: [
      "Dubai",
      "Abu Dhabi",
      "Sharjah",
      "Al Ain",
      "Ajman",
      "Ras Al Khaimah",
      "Fujairah",
      "Umm Al Quwain",
      "Khor Fakkan",
      "Dibba Al-Fujairah",
    ],
  },
  {
    name: "Turkey",
    code: "TR",
    cities: [
      "Istanbul",
      "Ankara",
      "Izmir",
      "Bursa",
      "Adana",
      "Gaziantep",
      "Konya",
      "Antalya",
      "Diyarbakir",
      "Mersin",
    ],
  },
  {
    name: "Iran",
    code: "IR",
    cities: [
      "Tehran",
      "Mashhad",
      "Isfahan",
      "Karaj",
      "Shiraz",
      "Tabriz",
      "Qom",
      "Ahvaz",
      "Kermanshah",
      "Urmia",
    ],
  },
  {
    name: "Iraq",
    code: "IQ",
    cities: [
      "Baghdad",
      "Basra",
      "Mosul",
      "Erbil",
      "Kirkuk",
      "Najaf",
      "Karbala",
      "Sulaymaniyah",
      "Nasiriyah",
      "Amarah",
    ],
  },
  {
    name: "Italy",
    code: "IT",
    cities: [
      "Rome",
      "Milan",
      "Naples",
      "Turin",
      "Palermo",
      "Genoa",
      "Bologna",
      "Florence",
      "Bari",
      "Catania",
    ],
  },
  {
    name: "Spain",
    code: "ES",
    cities: [
      "Madrid",
      "Barcelona",
      "Valencia",
      "Seville",
      "Zaragoza",
      "Málaga",
      "Murcia",
      "Palma",
      "Las Palmas",
      "Bilbao",
    ],
  },
  {
    name: "Netherlands",
    code: "NL",
    cities: [
      "Amsterdam",
      "Rotterdam",
      "The Hague",
      "Utrecht",
      "Eindhoven",
      "Tilburg",
      "Groningen",
      "Almere",
      "Breda",
      "Nijmegen",
    ],
  },
  {
    name: "Belgium",
    code: "BE",
    cities: [
      "Brussels",
      "Antwerp",
      "Ghent",
      "Charleroi",
      "Liège",
      "Bruges",
      "Namur",
      "Leuven",
      "Mons",
      "Aalst",
    ],
  },
  {
    name: "Switzerland",
    code: "CH",
    cities: [
      "Zurich",
      "Geneva",
      "Basel",
      "Lausanne",
      "Bern",
      "Winterthur",
      "Lucerne",
      "St. Gallen",
      "Lugano",
      "Biel/Bienne",
    ],
  },
  {
    name: "Austria",
    code: "AT",
    cities: [
      "Vienna",
      "Graz",
      "Linz",
      "Salzburg",
      "Innsbruck",
      "Klagenfurt",
      "Villach",
      "Wels",
      "Sankt Pölten",
      "Dornbirn",
    ],
  },
  {
    name: "Poland",
    code: "PL",
    cities: [
      "Warsaw",
      "Kraków",
      "Łódź",
      "Wrocław",
      "Poznań",
      "Gdańsk",
      "Szczecin",
      "Bydgoszcz",
      "Lublin",
      "Katowice",
    ],
  },
  {
    name: "Russia",
    code: "RU",
    cities: [
      "Moscow",
      "Saint Petersburg",
      "Novosibirsk",
      "Yekaterinburg",
      "Kazan",
      "Nizhny Novgorod",
      "Chelyabinsk",
      "Samara",
      "Omsk",
      "Rostov-on-Don",
    ],
  },
  {
    name: "Ukraine",
    code: "UA",
    cities: [
      "Kyiv",
      "Kharkiv",
      "Odesa",
      "Dnipro",
      "Donetsk",
      "Zaporizhzhia",
      "Lviv",
      "Kryvyi Rih",
      "Mykolaiv",
      "Mariupol",
    ],
  },
  {
    name: "Sweden",
    code: "SE",
    cities: [
      "Stockholm",
      "Gothenburg",
      "Malmö",
      "Uppsala",
      "Västerås",
      "Örebro",
      "Linköping",
      "Helsingborg",
      "Jönköping",
      "Norrköping",
    ],
  },
  {
    name: "Norway",
    code: "NO",
    cities: [
      "Oslo",
      "Bergen",
      "Stavanger",
      "Trondheim",
      "Drammen",
      "Fredrikstad",
      "Kristiansand",
      "Sandnes",
      "Tromsø",
      "Sarpsborg",
    ],
  },
  {
    name: "Denmark",
    code: "DK",
    cities: [
      "Copenhagen",
      "Aarhus",
      "Odense",
      "Aalborg",
      "Frederiksberg",
      "Esbjerg",
      "Randers",
      "Kolding",
      "Horsens",
      "Vejle",
    ],
  },
  {
    name: "Finland",
    code: "FI",
    cities: [
      "Helsinki",
      "Espoo",
      "Tampere",
      "Vantaa",
      "Oulu",
      "Turku",
      "Jyväskylä",
      "Lahti",
      "Kuopio",
      "Pori",
    ],
  },
  {
    name: "Greece",
    code: "GR",
    cities: [
      "Athens",
      "Thessaloniki",
      "Patras",
      "Heraklion",
      "Larissa",
      "Volos",
      "Ioannina",
      "Chania",
      "Chalcis",
      "Rhodes",
    ],
  },
  {
    name: "Portugal",
    code: "PT",
    cities: [
      "Lisbon",
      "Porto",
      "Amadora",
      "Braga",
      "Setúbal",
      "Coimbra",
      "Queluz",
      "Funchal",
      "Cacém",
      "Vila Nova de Gaia",
    ],
  },
  {
    name: "Singapore",
    code: "SG",
    cities: ["Singapore"],
  },
  {
    name: "Malaysia",
    code: "MY",
    cities: [
      "Kuala Lumpur",
      "George Town",
      "Ipoh",
      "Shah Alam",
      "Petaling Jaya",
      "Johor Bahru",
      "Malacca City",
      "Kota Kinabalu",
      "Kuching",
      "Seremban",
    ],
  },
  {
    name: "Thailand",
    code: "TH",
    cities: [
      "Bangkok",
      "Chiang Mai",
      "Phuket",
      "Pattaya",
      "Nonthaburi",
      "Hat Yai",
      "Pak Kret",
      "Nakhon Ratchasima",
      "Udon Thani",
      "Khon Kaen",
    ],
  },
  {
    name: "Vietnam",
    code: "VN",
    cities: [
      "Ho Chi Minh City",
      "Hanoi",
      "Da Nang",
      "Hai Phong",
      "Can Tho",
      "Bien Hoa",
      "Hue",
      "Nha Trang",
      "Buon Ma Thuot",
      "Vung Tau",
    ],
  },
  {
    name: "Philippines",
    code: "PH",
    cities: [
      "Manila",
      "Quezon City",
      "Davao City",
      "Caloocan",
      "Cebu City",
      "Zamboanga City",
      "Taguig",
      "Antipolo",
      "Pasig",
      "Cagayan de Oro",
    ],
  },
  {
    name: "Indonesia",
    code: "ID",
    cities: [
      "Jakarta",
      "Surabaya",
      "Bandung",
      "Medan",
      "Bekasi",
      "Semarang",
      "Palembang",
      "Makassar",
      "Tangerang",
      "Depok",
    ],
  },
  {
    name: "New Zealand",
    code: "NZ",
    cities: [
      "Auckland",
      "Wellington",
      "Christchurch",
      "Hamilton",
      "Tauranga",
      "Napier",
      "Dunedin",
      "Palmerston North",
      "Nelson",
      "Rotorua",
    ],
  },
  {
    name: "Israel",
    code: "IL",
    cities: [
      "Jerusalem",
      "Tel Aviv",
      "Haifa",
      "Rishon LeZion",
      "Petah Tikva",
      "Ashdod",
      "Netanya",
      "Beersheba",
      "Holon",
      "Bnei Brak",
    ],
  },
  {
    name: "Chile",
    code: "CL",
    cities: [
      "Santiago",
      "Valparaíso",
      "Concepción",
      "La Serena",
      "Antofagasta",
      "Temuco",
      "Rancagua",
      "Talca",
      "Arica",
      "Puerto Montt",
    ],
  },
  {
    name: "Colombia",
    code: "CO",
    cities: [
      "Bogotá",
      "Medellín",
      "Cali",
      "Barranquilla",
      "Cartagena",
      "Cúcuta",
      "Bucaramanga",
      "Pereira",
      "Santa Marta",
      "Ibagué",
    ],
  },
  {
    name: "Peru",
    code: "PE",
    cities: [
      "Lima",
      "Arequipa",
      "Trujillo",
      "Chiclayo",
      "Piura",
      "Iquitos",
      "Cusco",
      "Huancayo",
      "Chimbote",
      "Tacna",
    ],
  },
  {
    name: "Venezuela",
    code: "VE",
    cities: [
      "Caracas",
      "Maracaibo",
      "Valencia",
      "Barquisimeto",
      "Maracay",
      "Ciudad Guayana",
      "Barcelona",
      "Maturín",
      "Puerto La Cruz",
      "Petare",
    ],
  },
];

export function getCountries(): CountryData[] {
  return countriesData;
}

export function getCitiesByCountryCode(countryCode: string): string[] {
  const country = countriesData.find((c) => c.code === countryCode);
  return country ? country.cities : [];
}

export function searchCountries(query: string): CountryData[] {
  if (!query) return countriesData;

  const lowerQuery = query.toLowerCase();
  return countriesData.filter(
    (country) =>
      country.name.toLowerCase().includes(lowerQuery) ||
      country.code.toLowerCase().includes(lowerQuery)
  );
}

export function searchCities(countryCode: string, query: string): string[] {
  const cities = getCitiesByCountryCode(countryCode);
  if (!query) return cities;

  const lowerQuery = query.toLowerCase();
  return cities.filter((city) => city.toLowerCase().includes(lowerQuery));
}
